### ISSUE TITLE
Why does the XSP file format use a random nonce for each segment?

### ISSUE THREAD

**Issue by e1ven** [3nsoft/ecma-nacl#1]
I had requested that the libsodium project implement support for large files, perhaps using a variant of your XSP format (https://github.com/jedisct1/libsodium/issues/141), but they bring up a good point-

Since each segment has it's own authentication and nonce, it would seem possible for an attacker to rearrange/remove segments. Using the same key throughout, and an incrementing nonce would fix this problem.

I see that you advise "So, when encrypting many segments of a huge file, advance nonce oddly every time." earlier in the readme - Do you validate that this occurs for an XSP?

Why not just include the key once, and require, per-spec, that the nonce increases for each segment?

**Comment by 3nsoft** [comment]
New version 2.0.0 of the library has new XSP layout in line with discussion that happened in May 2014 on libsodium's thread.
Format protects against reshuffling of segments, yet it allows partial changes to file, so that nonces are never reused.
