### ISSUE TITLE
Message array m must be Uint8Array.

### ISSUE THREAD

**Issue by diadal** [3nsoft/ecma-nacl#12]
am getting this `Message array m must be Uint8Array.`
```
const skey = 'efdfs7343jdsawq7e23dxjaswyet34efdfdwe34'

function nextNon () {
  var nonce = new Uint8Array(24)
  crypto.getRandomValues(nonce)
  return nonce
}

Mycrypt.encrypt = (data) => { return nacl.secret_box.formatWN.pack(data, nextNon(), skey) }
MYcrypt.decrypt = (data) => { return nacl.secret_box.formatWN.open(data, skey) }
```

**Comment by diadal** [comment]
fixed

**Comment by 3n-mb** [comment]
Ya. skey should be Uint8Array.
@diadal I remember a show from mid 2010's with CryptoCat's bugs that were results of incorrect types in JavaScript code. This taught a valuable hard lesson to add assertions about types of incoming parameters in JavaScript.
TypeScript helps to right type-correct code. But even in TypeScript code we want to have run time checks of types arguments that may come from an outside of the library.
