### ISSUE TITLE
makeEncryptor and makeDecryptor bug

### ISSUE THREAD

**Issue by timothyjoelwright** [3nsoft/ecma-nacl#2]
nacl.box.formatWN.makeEncryptor and nacl.box.formatWN.makeDecryptor are missing the arrFactory guard statement so they fail with "TypeError: Cannot read property 'wipe' of undefined"

**Comment by 3nsoft** [comment]
Thank you for catching it.
It is fixed and pushed as part of v2.1.0. In it xsp segment's api is only taking in appropriate de(en)cryptors, instead of naked master keys.
