### ISSUE TITLE
m.subarray is not a function

### ISSUE THREAD

**Issue by chickahoona** [3nsoft/ecma-nacl#5]
When using scrypt, I always get "Error: m.subarray is not a function".

A fiddle to reproduce the error:
http://jsfiddle.net/e00h9tem/

(check console)

**Comment by 3n-mb** [comment]
@chickahoona `scrypt(pass, salt, ...)` takes `Uint8Array` for pass and salt, not strings. (Need better error throwing in parameter's checking?)

 1. In C, char[] is both a string, and a byte array. Thus, C examples have to be taken carefully.
 2. Password can be any language, and your application may use any encoding to put it into bytes. Do not restrict your user with choice for passwords. On node, I use Buffer's for this. In browser, while with nothing explicitly standard (correct me if I am wrong here), there is a utf-8 hack floating around.
