### ISSUE TITLE
Documentation for integration with Typings

### ISSUE THREAD

**Issue by jicksta** [3nsoft/ecma-nacl#6]
If I wish to use ecma-nacl in a TypeScript+Typings project, it seems I'd have to download (directly or with git submodules) the ecma-nacl files into my project and refer to the `.ts` source files directly in my own compiler toolchain.

Is this the recommended way to use ecma-nacl in a TypeScript project? Since you're already publishing the package to npm, wouldn't it be easier for everyone if you also published typings definitions for the project to npm or DefinitelyTyped?

**Comment by 3n-mb** [comment]
Last versions of this library already have `typings` set in [package.json, line 6](https://github.com/3nsoft/ecma-nacl/blob/master/package.json).
So, when you use library, you only need to included it as one of dependencies in [package.json (line 29 in example from 3NWeb spec server project)](https://github.com/3nsoft/spec-server/blob/master/package.json). There is no need for separate definition files to float around. This is true starting from around version 1.8 of Typescript.
Note also that [tsconfig.json in mentioned project](https://github.com/3nsoft/spec-server/blob/master/tsconfig.json) excludes `node_modules`, i.e. you do not want to refer directly to any `.ts`/`.d.ts` in `node_modules`.

When versions of Typescript were older, I used to have `.d.ts` file which was a semi-manual compilation. With newer versions of TS, definitions are picked from `typings` field. Library devs should put files from DefinitlyTyped into respective npm packages, simplifying both their efforts, and user's installation.

What TS version do you use, or, which version is buried in the tool chain?
Let me know if you have a problem, or any sort of confusion.
