### ISSUE TITLE
Signing fails if message is 64 or more chars long

### ISSUE THREAD

**Issue by chickahoona** [3nsoft/ecma-nacl#7]
I tried to sign a message and always ran into a weird problem. I could narrow it down to the following.

This returns a normal boolean like expected:

```
var pair = nacl.signing.generate_keypair(window.crypto.getRandomValues(new Uint8Array(32)));
nacl.signing.signature("123456789012345678901234567890123456789012345678901234567890123", pair.skey);
```

This throws an error:
```
var pair = nacl.signing.generate_keypair(window.crypto.getRandomValues(new Uint8Array(32)));
nacl.signing.signature("1234567890123456789012345678901234567890123456789012345678901234", pair.skey);
```

The error that I get when I try this:

```
ecma-nacl.min.js:1 Uncaught TypeError: r.subarray is not a function
    at Object.update (ecma-nacl.min.js:1)
    at Object.i [as signature] (ecma-nacl.min.js:3)
    at <anonymous>:1:27
```

The same problem occurs if you try to validate a message.
so this returns a normal boolean like expected:

```
nacl.signing.verify(
    new Uint8Array([244, 33, 185, 42, 141, 194, 29, 156, 209, 232, 181, 210, 123, 178, 119, 252, 115, 203, 102, 118, 73, 251, 97, 155, 78, 203, 204, 125, 250, 230, 110, 168, 54, 183, 61, 42, 225, 123, 48, 12, 184, 229, 177, 75, 1, 71, 12, 180, 133, 20, 22, 156, 63, 90, 34, 200, 186, 190, 113, 66, 121, 3, 140, 6]),
	"123456789012345678901234567890123456789012345678901234567890123",
    new Uint8Array([168, 227, 208, 0, 73, 37, 53, 45, 120, 185, 103, 179, 61, 108, 254, 246, 125, 54, 76, 241, 170, 248, 94, 102, 183, 84, 4, 185, 131, 69, 247, 98])
);
```

and this throws an error:
```
nacl.signing.verify(
    new Uint8Array([244, 33, 185, 42, 141, 194, 29, 156, 209, 232, 181, 210, 123, 178, 119, 252, 115, 203, 102, 118, 73, 251, 97, 155, 78, 203, 204, 125, 250, 230, 110, 168, 54, 183, 61, 42, 225, 123, 48, 12, 184, 229, 177, 75, 1, 71, 12, 180, 133, 20, 22, 156, 63, 90, 34, 200, 186, 190, 113, 66, 121, 3, 140, 6]),
	"1234567890123456789012345678901234567890123456789012345678901234",
    new Uint8Array([168, 227, 208, 0, 73, 37, 53, 45, 120, 185, 103, 179, 61, 108, 254, 246, 125, 54, 76, 241, 170, 248, 94, 102, 183, 84, 4, 185, 131, 69, 247, 98])
);
```

**Comment by 3n-mb** [comment]
@chickahoona  In each of these example you are passing one of the arguments as a string. But library expects `Uint8Array`'s everywhere.

The reason for binary-only API is simple: crypto deals with bytes. When API takes a string it has to do en(de)coding implicitly, breeding confusion. Hence, all inputs and outputs must be binary.

Let me point you to typescript signature of functions that you use:
- `nacl.signing.signature(...)` is [here](https://github.com/3nsoft/ecma-nacl/blob/master/src/lib/signing/sign.ts#L144)
- `nacl.signing.verify(...)` is [here](https://github.com/3nsoft/ecma-nacl/blob/master/src/lib/signing/sign.ts#L253)

**Comment by 3n-mb** [comment]
@chickahoona you uncovered that `nacl.signing.verify(...)` is taking second argument as if it is `Uint8Array`. This is not intended. I'll fix it.
Thank you.

**Comment by chickahoona** [comment]
Ahh ok, understood. I could fix it now. I found another thing but I'll open a separate issue for that.

Thanks a lot for the quick response.
